apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app: {{.Values.name}}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.name}}-deployment
    spec:
      containers:
      - name: {{.Values.name}}-deployment
        image: {{.Values.image}}
        securityContext:
          runAsUser: 0  
          allowPrivilegeEscalation: true
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "86Mi"
            cpu: "120"
